language: java
dist: bionic

jdk:
  - oraclejdk11

matrix:
  include:
    - jdk: oraclejdk11
      addons:
        sonarcloud:
          organization: "i2p"
      before_install:
        - sed -i "1iplugins {\n    id 'org.sonarqube' version '3.0'\n}\n" build.gradle
    - jdk: openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.sonar/cache/
    - .gradle

script:
  - travis_wait 45 |
    if [ "$TRAVIS_JDK_VERSION" == "oraclejdk11" ]; then
      ./gradlew sonarqube codeCoverageReport -Dsonar.verbose=true
    else
      ./gradlew check codeCoverageReport
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc:
    channels:
      - "chat.freenode.net#i2p-dev"
    on_success: change
    on_failure: always
